/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoriesTable: typeof import('./src/components/componentsCategories/CategoriesTable.vue')['default']
    CategoryFormDialog: typeof import('./src/components/componentsCategories/CategoryFormDialog.vue')['default']
    DeleteConfirmationDialog: typeof import('./src/components/DeleteConfirmationDialog.vue')['default']
    EntriesFormDialog: typeof import('./src/components/entries/EntriesFormDialog.vue')['default']
    EntriesTable: typeof import('./src/components/entries/EntriesTable.vue')['default']
    EntryFormDialog: typeof import('./src/components/entries/EntryFormDialog.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    ProductFormDialog: typeof import('./src/components/componentsProducts/ProductFormDialog.vue')['default']
    ProductsFormDialog: typeof import('./src/components/products/ProductsFormDialog.vue')['default']
    ProductsTable: typeof import('./src/components/componentsProducts/ProductsTable.vue')['default']
    ProviderFormDialog: typeof import('./src/components/componentsProviders/ProviderFormDialog.vue')['default']
    ProvidersTable: typeof import('./src/components/componentsProviders/ProvidersTable.vue')['default']
    PurchaseFormDialog: typeof import('./src/components/componentsPurchases/PurchaseFormDialog.vue')['default']
    PurchasesTable: typeof import('./src/components/componentsPurchases/PurchasesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleFormDialog: typeof import('./src/components/sales/SaleFormDialog.vue')['default']
    SalesTable: typeof import('./src/components/sales/SalesTable.vue')['default']
    UnitsFormDialog: typeof import('./src/components/units/UnitsFormDialog.vue')['default']
    UnitsTable: typeof import('./src/components/units/UnitsTable.vue')['default']
    UserFilters: typeof import('./src/components/componentsUsers/UserFilters.vue')['default']
    UserFormDialog: typeof import('./src/components/componentsUsers/UserFormDialog.vue')['default']
    UsersTable: typeof import('./src/components/componentsUsers/UsersTable.vue')['default']
    WarehouseFormDialog: typeof import('./src/components/warehouses/WarehouseFormDialog.vue')['default']
    WarehousesTable: typeof import('./src/components/warehouses/WarehousesTable.vue')['default']
  }
}
